export const scores = [
   {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/petit_papa_noel.mei",
  },
  {
    name: "Ah les crocodiles",
    author: "",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/Ah_les_crocodiles.mei",
  },
  {
    name: "Adagio d'Albinoni",
    author: "Albinoni Tomaso",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/albinoni-tomaso.mei",
  },
  {
    name: "Bourrée",
    author: "Bach Johann Sebastian",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/bourree.mei",
  },
  {
    name: "Oh Christmas Tree",
    author: "Traditionnel",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/O Christmas Tree.mei",
  },
  {
    name: "Ah ya zein آه يا زينO pretty one",
    author: "Compositeur",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/O pretty one.mei",
  },
  {
    name: "Preludes",
    author: "Georges Bizet",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/prelude.mei",
  },
  {
    name: "Sarabande en Sib Majeur",
    author: "Pachelbel Johann",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/sarabande-sib-majeur.mei",
  },
  {
    name: "The Swan",
    author: "Camille Saint-Saëns",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/The Swan.mei",
  },
  {
    name: "Twinkle Twinkle Little Star",
    author: "compositeur inconnu",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/Twinkle Twinkle Little Star.mei",
  },
  {
    name: "We wish you a merry christmas",
    author: "compositeur inconnu",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/classic/We-wish-you-a-merry-christmas.mei",
  },
  {
    name: "All by myself",
    author: "",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/All_by_myself.mei",
  },
  {
    name: "Bella Ciao",
    author: "",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Bella_Ciao.mei",
  },
  {
    name: "Hymn for the Week-end",
    author: "Coldplay",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Coldplay_-_Hymn_for_the_Weekend.mei",
  },
  {
    name: "Comme d'habitude ",
    author: "Jacques Revaux Claude François",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Comme_d_habitude.mei",
  },
  {
    name: "Douce dame jolie",
    author: "Middenstem",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Douce dame jolie.mei",
  },
  {
    name: "Fly me to the moon",
    author: "Bart Howard",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Fly_me_to_the_moon.mei",
  },
  {
    name: "Formidable",
    author: "Stromae",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Formidable.mei",
  },
  {
    name: "Humpty Dumpty",
    author: "compositeur inconnu",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Humpty Dumpty.mei",
  },
  {
    name: "Je l'aime à mourir ",
    author: "Francis Cabrel & Luis Gomez-Escolar",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Je_l_aime_à_mourir.mei",
  },
  {
    name: "Last Christmas",
    author: "",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Last_Christmas.mei",
  },
  {
    name: "Marry had a little limb",
    author: "Compositeur inconnu",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Marry had a little limb.mei",
  },
  {
    name: "The Rocky Road to Dublin",
    author: "Traditional Irish Folksong",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/The Rocky Road to Dublin.mei",
  },
  {
    name: "Yellow Submarine",
    author: "The Beatles",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/pop/Yellow_Submarine.mei",
  },
  {
    name: "Avatar theme",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Avatar_theme.mei",
  },
  {
    name: "Batman theme (Batman The Dark Knight)",
    author: "Hans Zimmer",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Batman_The_Dark_Knight_Theme.mei",
  },
  {
    name: "Belle (Belle et sébastien)",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Belle (Belle et Sébastien).mei",
  },
  {
    name: "Blue Bird Naruto Shippudden",
    author: "Taha IDK",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Blue Bird Naruto Shippudden.mei",
  },
  {
    name: "City of stars (LaLaLand)",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/City_of_Stars.mei",
  },
  {
    name: "Fairy Tail theme",
    author: "Yasuharu Takanashi",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Fairy_Tail_Main_theme.mei",
  },
  {
    name: "Game of thrones Generique",
    author: "Ramin Djawadi",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Game_of_Thrones.mei",
  },
  {
    name: "Harry Potter Theme",
    author: "John Williams",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Harry_Potter_Theme_easy.mei",
  },
  {
    name: "Hes a pirate easy",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Hes_a_pirate_easy.mei",
  },
  {
    name: "I ll be there for you (Friends)",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/I_ll be there for you (Friends).mei",
  },
  {
    name: "Kaamelott Generique",
    author: "Alexandre Astier",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Kaamelott_Générique_Livre_V.mei",
  },
  {
    name: "Les Aristochats",
    author: "George Bruns",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Les_Aristochats.mei",
  },
  {
    name: "Metal Gear Solid Theme",
    author: "Harry-Gregson Williams",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Metal_Gear_Solid_Theme.mei",
  },
  {
    name: "Oogway Ascends (Kung Fu Panda)",
    author: "Hans Zimmer",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Oogway_ascends.mei",
  },
  {
    name: "Poupée de cire, Poupée de son (Les demoisselles de Rochefort)",
    author: "Serge Gainsbourg",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Poupée_de_cire,_poupée_de_son.mei",
  },
  {
    name: "Princesse mononoke Theme",
    author: "Joe Hisaishi",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Princesse_Mononoké.mei",
  },
  {
    name: "rafiqi-izani-faiz-renji-dan-dan-kokoro-hikaretaku",
    author: "compositeur inconnu",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/rafiqi-izani-faiz-renji-dan-dan-kokoro-hikaretaku.mei",
  },
  {
    name: "Reality (La Boum)",
    author: "Vladimir Cosma",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Reality.mei",
  },
  {
    name: "The avengers theme",
    author: "Alan Silvestri",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/The_avengers_theme.mei",
  },
  {
    name: "The Force Theme (Star Wars)",
    author: "John Williams",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/The_Force_Theme_Star_Wars.mei",
  },
  {
    name: "Unravel (Tokyo Ghoul)",
    author: "TK",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Unravel (Tokyo Ghoul).mei",
  },
  {
    name: "Vois sur ton chemin (Les Choristes)",
    author: "Bruno Coulais",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Vois_sur_ton_chemin_Les_Choristes.mei",
  },
  {
    name: "When you believe (Le Prince d'Egypte)",
    author: "Stephen Schwartz",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/When_you_believe (Le Prince d_Egypte).mei",
  },
  {
    name: "Where no one goes (Dragon)",
    author: "John Powell & Jonsi",
    style: "film",
    styleClass: "movie",
    path: "/assets/scores/film/Where_no_one_goes (Dragon).mei",
  },
  {
    name: "Amen",
    author: "compositeur inconnu",
    style: "jazz",
    styleClass: "jazz",
    path: "/assets/scores/jazz/Amen.mei",
  },
  {
    name: "Boogie Woogie",
    author: "compositeur inconnu",
    style: "jazz",
    styleClass: "jazz",
    path: "/assets/scores/jazz/Boogie-Woogie.mei",
  },{
    name: "Hit the road Jack",
    author: "Ray Charles",
    style: "jazz",
    styleClass: "jazz",
    path: "/assets/scores/jazz/Hit_the_road_Jack.mei",
  },{
    name: "Tea for two",
    author: "Voncent Youmans",
    style: "jazz",
    styleClass: "jazz",
    path: "/assets/scores/jazz/Tea_for_two.mei",
  },
  {
    name: "San Tropez",
    author: "Pink Floyd",
    style: "rock",
    styleClass: "rock",
    path: "/assets/scores/rock/San_Tropez.mei",
  },
  {
    name: "The sound of Silence",
    author: "Simon & Garfunkel",
    style: "rock",
    styleClass: "rock",
    path: "/assets/scores/rock/The_sound_of_Silence_facile.mei",
  },
  {
    name: "Viva la vida",
    author: "Coldplay",
    style: "rock",
    styleClass: "rock",
    path: "/assets/scores/rock/Viva_la_vida.mei",
  },
]

