export const scores = [
   {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Crisantemi",
    author: "Giacomo Puccini",
    style: "pop",
    styleClass: "pop",
    path: "/assets/scores/crisantemi.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
  {
    name: "Au clair de la lune",
    author: "Jean-Baptiste Lully",
    style: "classique",
    styleClass: "classic",
    path: "/assets/scores/petit_papa_noel.mei",
  },
]

